pings:
  hosts:
  - host: 10.12.12.1
    name: Server VLAN Gateway
    isgateway: true
  - host: 10.12.99.1
    name: Jail VLAN Gateway
    isgateway: true
  - host: 172.16.100.1
    name: Infra VLAN Gateway
    isgateway: true
  - host: 192.168.12.1
    name: User VLAN Gateway
    isgateway: true
  - host: 192.168.12.1
    name: App Server
    isgateway: true
  - host: 8.8.8.8
    name: Google DNS
  - host: 10.12.12.20
    name: printer-kiga-gramschatz
  - host: 10.12.12.30
    name: voip-kiga-gramschatz
  - host: 10.12.12.10
    name: appserver-kiga-gramschatz
  - host: 10.12.12.11
    name: backup-kiga-gramschatz
  - host: 172.16.100.100
    name: openwisp-kiga-gramschatz
  update_interval: 10 
  timeout: 2 
range_scanner:
  interface: wlan0
  update_interval: 2
  update_details: 5
  ssid:
    - name: "Spezialgelagertes Sonder-WLAN"
    - name: "Ahorn Kindergarten Gramschatz"

report_path: "/mnt/dietpi_userdata/downloads/"