pings:
  hosts:
  - host: 10.12.12.1
    name: Server VLAN Gateway
  - host: 10.12.99.1
    name: Jail VLAN Gateway
  - host: 172.16.100.1
    name: Infra VLAN Gateway
  - host: 192.168.12.1
    name: User VLAN Gateway
  - host: 8.8.8.8
    name: Google DNS
  update_interval: 10 
  timeout: 2 
range_scanner:
  interface: wlan0
  update_interval: 2
  update_details: 5
  ssid:
    - name: "Spezialgelagertes Sonder-WLAN"
    - name: "Ahorn Kindergarten Gramschatz"

report_path: "/mnt/dietpi_userdata/downloads/"